### ISSUE TITLE
Bug: second-layer replies sometimes count for floor numbers, sometimes don't

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#495]
In some topics, the 2-layer replies don't take the floor numbers, like: https://forum.casbin.com/t/97#r_320

![image](https://user-images.githubusercontent.com/3787410/163752589-d2f0f1fe-329f-4aa4-8c41-ff4e9dd4294c.png)

But in some other topics, they count: https://forum.casbin.com/t/46#r_339

![image](https://user-images.githubusercontent.com/3787410/163752631-bf86e8d8-2e26-41a1-ab1b-3fd3dc59bb21.png)

Why they have different behaviors?

**Comment by hsluoyz** [comment]
@Nekotoxin @RyaoChengfeng

**Comment by RyaoChengfeng** [comment]
Their behavior is actually the same: the replies don't take the floor numbers in all topics. 
At https://forum.casbin.com/t/46#r_339, just because the 23 and 24 floors were deleted, only the 25 floor was shown. It can also be seen here: https://forum.casbin.com/t/46#r_232
![image](https://user-images.githubusercontent.com/69711608/163756529-b67dc308-ad0d-4ce1-991e-575468c82922.png)

The situation is also common in Baidu Tieba .I think there is no problem with it. It doesn't require any modification.
