### ISSUE TITLE
[backend] replace the existing cloud OSS storage provider with rclone

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#584]
Casibase will use rclone (as Go SDK) to access different storage providers: https://github.com/rclone/rclone#storage-providers

![image](https://github.com/casbin/casibase/assets/3787410/f95780f2-5850-4852-b860-f9ebe5170355)

Initial code is here (generated by ChatGPT): https://github.com/casbin/casibase/blob/master/storage/rclone.go 

The above code doesn't work yet. Need to improve and test, finally replace the existing Aliyun OSS code: https://github.com/casbin/casibase/blob/master/storage/aliyun.go

**Comment by wintbiit** [comment]
I'm trying to work on this. Use Casdoor `Resource-API` or `Provider-API and then manually interact with it`? I prefer former. But Casdoor Resource API seems to be User-Oriented (judged by [query params](https://github.com/casdoor/casdoor/blob/3d4ca1adb17ce1b7d799a2965e4f1ac99a3d994e/controllers/resource.go#L35C1-L43C41) ) instead of  Application-Oriented (get resources by application is not supported). 

So I've been quite confused both on how to `Use Casdoor storage API` and the design idea of Casdoor Resource-API. @hsluoyz

**Comment by hsluoyz** [comment]
@WinterOfBit use Casdoor Resource API by calling the casdoor-go-sdk: https://github.com/casdoor/casdoor-go-sdk/blob/master/casdoorsdk/resource.go , the SDK already handles the authentication (via app's client ID and secret)

**Comment by hsluoyz** [comment]
@WinterOfBit hi, sorry for the trouble here, but we decided again to use Casdoor Storage API. Could you create the previous PR again here? Thanks!

**Comment by wintbiit** [comment]
> @WinterOfBit hi, sorry for the trouble here, but we decided again to use Casdoor Storage API. Could you create the previous PR again here? Thanks!

ok. I'll re-check my commits and make another pr😦

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casibase/pull/594
